### ISSUE TITLE
Choosing adapters on inference

### ISSUE THREAD

**Issue by raihan0824** [S-LoRA/S-LoRA#12]
Hi, thanks for the great work.

Is it possible to use certain adapters while inferring? From the paper, it seems like the adapters are chosen randomly on inference. Would be great if adapters can be a parameter while inferring.

Thank you

**Comment by Ying1123** [comment]
> Hi, thanks for the great work.
> 
> Is it possible to use certain adapters while inferring? From the paper, it seems like the adapters are chosen randomly on inference. Would be great if adapters can be a parameter while inferring.
> 
> Thank you

After launching the server that include the adapter you want to serve, you can send the request with a specified adapter by setting the `lora_dir` field :
https://github.com/S-LoRA/S-LoRA/blob/184b5a87f7e169b9b92188ad927e41fae684b808/benchmarks/run_exp.py#L59-L70

You can use the following command to launch the server:
```
python -m slora.server.api_server --max_total_token_num {num_token}  --model {base_model_dir} --tokenizer_mode auto --lora {adapter_dir1} --lora {adapter_dir2} —swap
```
Where `num_token` is the size of the unified memory pool, which should be manually adjusted.

**Comment by BaiStone2017** [comment]
> adapters

In your question, means choose adater is random?How is it reflected in the paper?
