### ISSUE TITLE
Encountered some problems when adding the support for GPT-Q 4-bit quantized LLaMA-2 model.

### ISSUE THREAD

**Issue by suilin0432** [S-LoRA/S-LoRA#18]
Hi~ Thanks for your great job! It’s really useful and important to serve many LoRA adapters in the real world.

In order to further reduce the **resource constraints** (e.g. GPU memory & computation resources), I'm working on adding support for **quantized LLaMA-2 model** at [[here](https://github.com/suilin0432/S-LoRA/tree/develop_quant_llama)](https://github.com/suilin0432/S-LoRA/tree/develop_quant_llama). 

I noticed that the **TGI**(text-generation-inference) framework has good support for **GPT-Q quantized LLM models**, hence, I start from **borrowing ideas** from TGI to introduce quantized LLM models support into S-LoRA framework.

I put some effort into this thing, and successfully support the GPT-Q quantized LLaMA-2 model with **QuantLinear**.

However I encountered some problems when using the **exllama kernels**.

### Problem

First of all, I pass the `--no-lora-compute` into S-LoRA and use TGI to compare the generated results. When inputting some simple prompts such as "Hello~" or "Nice to meet you", I can align the generated sentences with results generated by TGI. However, the model always generates **NaN tensors** after the **first** transformer layer.

The following block shows an example of the error message.

```python
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<RouterManager.loop_for_fwd() done, defined at /data1/bak/suilin/codes/S-LoRA/slora/server/router/manager.py:153> exception=RuntimeError('probability tensor contains either `inf`, `nan` or element < 0')>
Traceback (most recent call last):
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/manager.py", line 156, in loop_for_fwd
    await self._step()
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/manager.py", line 197, in _step
    await self._prefill_batch(self.running_batch)
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/manager.py", line 252, in _prefill_batch
    ans = await asyncio.gather(*rets)
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/model_infer/model_rpc.py", line 469, in prefill_batch
    ans = self._prefill_batch(batch_id)
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/model_infer/model_rpc.py", line 164, in exposed_prefill_batch
    return self.forward(batch_id, is_prefill=True)
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/model_infer/model_rpc.py", line 252, in forward
    next_token_ids, next_token_probs = sample(logits, batch)
  File "/data1/bak/suilin/codes/S-LoRA/slora/server/router/model_infer/post_process.py", line 15, in sample
    sampled_index = torch.multinomial(probs_sort, num_samples=1, replacement=True)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

After debugging for a while, I find that the value of `q` tensor is wrong after performing `q = base_layer_weight.q_layer(input_embs.view(-1, base_layer_infer.embed_dim_))`.

When we input two prompt "What is the meaning of the" and "What is the meaning of the cat?", features of the former several tokens, should be the **same**. However the value of `q` changed dramatically after I only append the word"cat" at the end of the prompt.

Can anyone give me some advice?

### Environment

```python
Pytorch Version: 2.0.1
CUDA Version: 11.7
Driver Version: 515.48.07

Base Model: TheBloke/Llama-2-7B-Chat-GPTQ
Lora Weight: tloen/alpaca-lora-7b & MBZUAI/bactrian-x-llama-7b-lora

```

### Modifications to Support Quantized LLaMA-2 model

In order to support the GPT-Q Quantized LLaMA-2 model, I make the following main modifications:

1. Add `slora/models/llama2_quant/`: GPT-Q quantized LLaMA-2 model implementations.
2. Add `slora/models/gptq`: Code to support gptq, modified from TGI.
3. Add `slora/models/exllama_kernels`: Code to support gptq-exllama, modified from TGI.
4. Add `slora/models/peft/lora_unordered_batch_infer_gptq.py`: rewrite `_batch_lora_get_qkv`, `_lora_get_qkv`, `_batch_lora_get_o` and `_lora_get_o` functions.
5. Modify `slora/mprophet/model_config.py`: add `get_quantize_config_json` for dummy quantized models.
6. Modify `slora/utils/model_load.py`: add `hf_load_quantize_config` to load quantize config.
7. Modify `slora/server/router/model_infer/model_rpc.py`: add conditional branchs to use `QuantLlama2TpPartModel` and `LoraUnorderedBatchInferGPTQ`.

TODO: The inference speed is not as fast as I expected when passed `--no-lora-compute` flag. Need to find the reason.

You could use the following command line to build the api_server. `USE_EXLLAMA` is used to control whether to use exllama.

```python
USE_EXLLAMA=False CUDA_VISIBLE_DEVICES=1 python -m slora.server.api_server --max_total_token_num 10000 --model ${BASE_PATH}/Llama-2-7B-Chat-GPTQ --tokenizer_mode auto --swap --lora ${BASE_PATH}/alpaca-lora-7b-0 --lora ${BASE_PATH}/bactrian-x-llama-7b-lora-0 --mode gptq --port 19283 --nccl_port 18277 --no-lora-compute
```

Some code implementations are not reasonable. For example, currently I use passed `gptq` to the `--mode` arg to use GPTQ quantized model.

Could you please give me some **suggestions** in order to better contribute to the S-LoRA community? I'd like to open a PR after some modifications.

**Comment by nikshepsvn** [comment]
Check out https://github.com/predibase/lorax
