### ISSUE TITLE
This is huge!

### ISSUE THREAD

**Issue by yhyu13** [S-LoRA/S-LoRA#2]
Hi,

I came across this paper on youtube https://www.youtube.com/watch?v=2dSFP84rVfY 

I believe this work could be transcendental to cost effective LoRA model severing. Since you have made comparisons to PEFT and vLLM, is there any chance that this work goes into one of popular open source model severing frameworks?

**Comment by michaelfeil** [comment]
Can't agree more. Amazing work! Contributor to tgi-forks, vllm, and ctranslate2 -> would absolutely love to have this thing running with vLLM, any pointers?

**Comment by Ying1123** [comment]
@yhyu13 @michaelfeil Thanks for your interest! Integrating SLoRA into vLLM is in the plan.

**Comment by tjtanaa** [comment]
May I know has this plan been set into motion?

**Comment by Ying1123** [comment]
> May I know has this plan been set into motion?

The change is planed in December.

**Comment by tjtanaa** [comment]
> > May I know has this plan been set into motion?
> 
> The change is planned to be done in December.

Great to know this. I bet the whole community will be in uproar when it is in the vllm.
