### ISSUE TITLE
What's the difference from LoRAX

### ISSUE THREAD

**Issue by wDevil** [S-LoRA/S-LoRA#22]
Hi, thanks for your great job! 
Can you help me to understand what's the difference from LoRAX project https://github.com/predibase/lorax

**Comment by peterarends** [comment]
This might help: [https://github.com/predibase/lorax/issues/90 
](https://github.com/predibase/lorax/issues/90)

(not affiliated with LoRAX but was wondering the same thing)

**Comment by wDevil** [comment]
thanks!
