### ISSUE TITLE
Tensor parallelism with S-LoRA

### ISSUE THREAD

**Issue by debraj135** [S-LoRA/S-LoRA#27]
We have found this work to be very inspiring and I have been looking into how to leverage this for various adapters available on huggingface. 

I noticed that tensor parallelism over multiple-gpus with multiple-adapters is currently not supported by S-LoRA. I wanted to confirm if my understanding is correct.

**Comment by Ying1123** [comment]
Hi, @debraj135, thanks for your interest. The tensor parallelism is not supported in the main branch. We have a draft version in the `tp` branch. We'll merge it into the main branch in two weeks.
