### ISSUE TITLE
torch 2.0.1 requires triton==2.0.0 

### ISSUE THREAD

**Issue by giaosudau** [S-LoRA/S-LoRA#8]
Got this after `pip install torch==2.0.1` then `pip install -e .` 

Can I use different torch version to use `triton==2.1.0`

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.0.1 requires triton==2.0.0; platform_system == "Linux" and platform_machine == "x86_64", but you have triton 2.1.0 which is incompatible.
```

**Comment by Ying1123** [comment]
This error can be ignored, but please keep using triton=2.1.0. The program should still be able to run. And, it should be fine to use other torch version.
